apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    apptype: webapp
  name: nginx-multi
spec:
  containers:
  - image: nginx
    name: nginx1
    ports:
    - containerPort: 80
  - image: curlimages/curl
    name: curl
    args:
    - sh    
    - -c 
    - sleep 3600    
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}