apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-curl
  name: pod-curl
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-curl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}