apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
      nodeSelector:
        disktype: ssd
status: {}