apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab3-node-affinity
  name: lab3-node-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-affinity
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - "large"
                      - "medium"            
status: {}