apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dp-pod-affinity
  name: dp-pod-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-pod-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-pod-affinity
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                    - "db"
              topologyKey: kubernetes.io/hostname
status: {}