apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: my-nginx
spec:
  containers:
  - args:
    - client
    image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
  nodeSelector:
    disktype: ssd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}