apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db-pod
spec:
  containers:
  - image: nginx
    name: db-pod
    resources: {}
  nodeName: viettq-worker1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

