apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-toleration
  name: pod-toleration
spec:
  containers:
  - image: nginx
    name: pod-toleration
    resources: {}
  nodeName: viettq-worker1
  tolerations:
  - key: "app"
    operator: Equal
    value: "special"
    effect: NoSchedule
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}