apiVersion: v1 
kind: Service 
metadata:
  name: service-nodeport
spec:   
  type: nodePort          
  selector:               
    app: nginx-deployment    
  ports: 
    - targetPort: 8080      
      port: 80           
      nodePort: 30888     