apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service 
spec: 
  type: ClusterIP          
  selector:               
    name: nginx-deployment    
  ports: 
    - targetPort: 80      
      port: 80           