apiVersion: v1
kind: PersistentVolume
metadata:  
  name: viettq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Mi
  nfs:
    path: /data2/delete/viettq-pv #Path in NFS Data path
    server: 192.168.30.10 #IP of NFS server
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: viettq-pvc