apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  labels:
    app: samplepod1
spec:  
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', "echo This-is-init-container"]
  containers:
  - name: nginx
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 20Mi    
    ports:
    - containerPort:  80
      name:  http    
  restartPolicy: Always    