apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    apptype: frontend
spec:
  containers:
    - name: nginx-container
      ports:
      - containerPort:  80
        name:  http
