apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30999
  selector:
    app: my-app
    apptype: frontend
